echo runAll

echo Yukon_Delta - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Yukon_Delta -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Yukon_Delta -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" --cloudmask_suffix toa.cloudmask.v1.2.tif -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07212022/Yukon_Delta --debug 1 --cloudmask &

echo Fairbanks - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Fairbanks -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Fairbanks -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Fairbanks --debug 1 --cloudmask &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Fairbanks -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Fairbanks -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Fairbanks --debug 1 --cloudmask &

echo Siberia - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Siberia -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Siberia -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Siberia --debug 1 --cloudmask &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Siberia -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Siberia -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Siberia --debug 1 --cloudmask &

echo Senegal - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Senegal -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Senegal -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Senegal --debug 1 --cloudmask &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Senegal -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Senegal -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Senegal --debug 1 --cloudmask &

echo Alaska-WV02 - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Alaska-WV02 -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Alaska -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Alaska-WV02 --debug 1 --cloudmask &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Alaska-WV02 -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Alaska -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Alaska-WV02 --debug 1 --cloudmask &

echo Howland-WV02 - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Howland-WV02 -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Howland -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Howland-WV02 --debug 1 --cloudmask &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Howland-WV02 -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Howland -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Howland-WV02 --debug 1 --cloudmask &

#echo Whitesands - ccdc_v2022062020
#echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Whitesands-WV02 -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Whitesands -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Whitesands-WV02 --debug 1 --cloudmask &
#python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Whitesands-WV02 -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Whitesands -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/Whitesands-WV02 --debug 1 --cloudmask &

echo RailroadValley-WV02 - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/RailroadValley-WV02 -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/RailroadValley-WV02 -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/RailroadValley-WV02 --debug 1 --cloudmask &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/RailroadValley-WV02 -target_dir /adapt/nobackup/people/mmacande/srlite/srlite_shared/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/RailroadValley-WV02 -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07042022/RailroadValley-WV02 --debug 1 --cloudmask &

echo finished

