echo runAll
# ls -alt /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/
#xrwxrwx. 1 gtamkin ilab   63 Jun  5 18:07 Yukon_Delta -> /adapt/nobackup/projects/ilab/projects/srlite/input/Yukon_Delta
#lrwxrwxrwx. 1 gtamkin ilab   62 Jun  5 18:07 Whitesands -> /adapt/nobackup/projects/ilab/projects/srlite/input/Whitesands
#lrwxrwxrwx. 1 gtamkin ilab   59 Jun  5 18:07 Siberia -> /adapt/nobackup/projects/ilab/projects/srlite/input/Siberia
#lrwxrwxrwx. 1 gtamkin ilab   59 Jun  5 18:07 Senegal -> /adapt/nobackup/projects/ilab/projects/srlite/input/Senegal
#lrwxrwxrwx. 1 gtamkin ilab   66 Jun  5 18:07 RailroadValley -> /adapt/nobackup/projects/ilab/projects/srlite/input/RailroadValley
#lrwxrwxrwx. 1 gtamkin ilab   59 Jun  5 18:07 Laselva -> /adapt/nobackup/projects/ilab/projects/srlite/input/Laselva
#lrwxrwxrwx. 1 gtamkin ilab   59 Jun  5 18:07 Howland -> /adapt/nobackup/projects/ilab/projects/srlite/input/Howland
#lrwxrwxrwx. 1 gtamkin ilab   58 Jun  5 18:07 Alaska -> /adapt/nobackup/projects/ilab/projects/srlite/input/Alaska

echo Yukon_Delta - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Yukon_Delta -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Yukon_Delta -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Yukon_Delta --debug 1 --cloudmask --regressor simple &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Yukon_Delta -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Yukon_Delta -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Yukon_Delta --debug 1 --cloudmask --regressor simple &

echo Whitesands - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Whitesands -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Whitesands -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Whitesands --debug 1 --cloudmask --regressor simple &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Whitesands -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Whitesands -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Whitesands --debug 1 --cloudmask --regressor simple &

echo Siberia - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Siberia -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Siberia -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Siberia --debug 1 --cloudmask --regressor simple &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Siberia -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Siberia -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Siberia --debug 1 --cloudmask --regressor simple &

echo Senegal - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Senegal -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Senegal -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Senegal --debug 1 --cloudmask --regressor simple &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Senegal -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Senegal -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Senegal --debug 1 --cloudmask --regressor simple &
echo RailroadValley - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/RailroadValley -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/RailroadValley -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/RailroadValley --debug 1 --cloudmask --regressor simple &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/RailroadValley -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/RailroadValley -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/RailroadValley --debug 1 --cloudmask --regressor simple &

echo Laselva - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Laselva -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Laselva -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Laselva --debug 1 --cloudmask --regressor simple &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Laselva -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Laselva -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Laselva --debug 1 --cloudmask --regressor simple &

echo Howland - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Howland -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Howland -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Howland --debug 1 --cloudmask --regressor simple &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Howland -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Howland -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Howland --debug 1 --cloudmask --regressor simple &

echo Alaska - ccdc_v2022062020
echo python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Alaska -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Alaska -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Alaska --debug 1 --cloudmask --regressor simple &
python ./srlite/view/SrliteWorkflowCommandLineView.py -toa_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/toa/Alaska -target_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/ccdc/ccdc_v20220620 -cloudmask_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/cloudmask/Alaska -bandpairs "[['blue_ccdc', 'BAND-B'], ['green_ccdc', 'BAND-G'], ['red_ccdc', 'BAND-R'], ['nir_ccdc', 'BAND-N']]" -output_dir /gpfsm/ccds01/nobackup/projects/ilab/data/srlite/products/srlite-0.9.10-07042022-mode-warp/07052022/Alaska --debug 1 --cloudmask --regressor simple &
